CREATE TABLE [dbo].[APODERARO]
(
	[id] INT NOT NULL PRIMARY KEY, 
    [Nombre] NVARCHAR(50) NOT NULL, 
    [Telefono] NVARCHAR(50) NOT NULL, 
    [id_Alumno] INT NOT NULL, 
    CONSTRAINT [FK_APODERARO_ALUMNO] FOREIGN KEY ([id_Alumno]) REFERENCES [ALUMNO]([id])
)
