CREATE TABLE [dbo].[INSCRITO]
(
	[id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [id_Alumno] INT NULL, 
    [Cod_Curso] INT NULL, 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([id_Alumno]) REFERENCES [Alumno]([id]), 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([Cod_Curso]) REFERENCES [CURSO]([cod])
)
